server {
    listen localhost:1033;
    server_name abdo;
    client_max_body_size 100;
    error_page 400 /www/error-pages/400.html;
    error_page 403 /www/error-pages/403.html;
    error_page 404 /www/error-pages/404.html;
    error_page 405 /www/error-pages/405.html;
    error_page 408 /www/error-pages/408.html;
    error_page 413 /www/error-pages/413.html;
    error_page 500 /www/error-pages/500.html;
    error_page 504 /www/error-pages/504.html;
 
    location / {
        root /www;
        methods GET DELETE;
        index index.html;
        autoindex on;
    }

    location /redirect {
        return 301 https://google.com;
    }

    location /cgi/ {
        root /www;
        methods GET POST DELETE;
        index index.html;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .sh /usr/bin/bash;
        cgi_pass .rb /usr/bin/ruby;
        cgi_pass .php /usr/bin/php;
        cgi_pass .pl /usr/bin/perl;
        autoindex on;
    }

    location /upload/ {
        root /www;
        methods GET POST DELETE;
        index index.html;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .sh /usr/bin/bash;
        cgi_pass .rb /usr/bin/ruby;
        cgi_pass .php /usr/bin/php;
        cgi_pass .pl /usr/bin/perl;
        autoindex on;
    }
}

server {
    listen localhost:1037;
    server_name aabdo;
    client_max_body_size 1;
    error_page 400 /www/error-pages/400.html;
    error_page 403 /www/error-pages/403.html;
    error_page 404 /www/error-pages/404.html;
    error_page 405 /www/error-pages/405.html;
    error_page 408 /www/error-pages/408.html;
    error_page 413 /www/error-pages/413.html;
    error_page 500 /www/error-pages/500.html;
    error_page 504 /www/error-pages/504.html;

    location / {
        root /www;
        methods GET POST DELETE;
        autoindex on;
    }

    location /upload/ {
        root /www/test;
        methods GET POST DELETE;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .sh /usr/bin/bash;
        cgi_pass .rb /usr/bin/ruby;
        cgi_pass .php /usr/bin/php;
        cgi_pass .pl /usr/bin/perl;
        autoindex on;
    }
}

