server {
    listen localhost:1033;
    server_name abdo;
    client_max_body_size 1000000;
    error_page 400 /www/400_badrequest.html;

    location / {
        root /www;
        methods GET DELETE;
        index index.html;
        autoindex on;
    }

    location /cgi/ {
        root /www;
        methods GET POST DELETE;
        index index.html;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .sh /usr/bin/bash;
        cgi_pass .rb /usr/bin/ruby;
        cgi_pass .php /usr/bin/php;
        cgi_pass .pl /usr/bin/perl;
        autoindex on;
    }

    location /upload/ {
        root /www;
        methods GET POST DELETE;
        index index.html;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .sh /usr/bin/bash;
        cgi_pass .rb /usr/bin/ruby;
        cgi_pass .php /usr/bin/php;
        cgi_pass .pl /usr/bin/perl;
        autoindex on;
    }
}

server {
    listen localhost:1033;
    server_name aabdo;
    client_max_body_size 1000000;
    error_page 400 /www/400_badrequest.html;

    location / {
        root /www;
        methods GET DELETE;
        autoindex on;
    }

    location /upload/ {
        root /www;
        methods GET DELETE;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .sh /usr/bin/bash;
        cgi_pass .rb /usr/bin/ruby;
        cgi_pass .php /usr/bin/php;
        cgi_pass .pl /usr/bin/perl;
        autoindex on;
    }

    location /aba/ {
        root /www;
        methods GET POST DELETE;
        autoindex on;
    }
}