server {
    listen localhost:1099;
    server_name one;
    client_max_body_size 1000000;
    error_page 400 /www/400_badrequest.html;

    location / {
        root /www1;
        methods GET DELETE;
        index index.html;
        autoindex on;
    }
}

server {
    listen localhost:1099;
    server_name two;
    client_max_body_size 1000000;
    error_page 400 /www/400_badrequest.html;

    location / {
        root /www2;
        methods GET DELETE;
        index index.html;
        autoindex on;
    }

    location /only2/ {
        root /www2;
        methods GET DELETE;
        index only2.html;
        autoindex on;
    }
}
